name: firebase_admin_interop
description: Firebase Admin SDK for Dart written as a wrapper around official Node.js SDK.
version: 2.1.0
homepage: https://github.com/pulyaevskiy/firebase-admin-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  js: ^0.6.1+1
  
  node_interop: ^2.0.2
  meta: ^1.1.8
  quiver_hashcode: ^2.0.0

dev_dependencies:
  test: ^1.17.10
  build_runner: ^2.0.5
  build_web_compilers: ^3.0.0
  build_test: ^2.1.2
