name: firebase_admin_interop
description: Firebase Admin SDK for Dart written as a wrapper around official Node.js SDK.
version: 2.1.0
homepage: https://github.com/pulyaevskiy/firebase-admin-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js: ^0.6.7
  
  node_interop: ^2.1.0
  meta: ^1.8.0
  quiver_hashcode: ^3.0.0+1

dev_dependencies:
  test: ^1.24.3
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  build_test: ^2.2.1
